name: CI/CD Pipeline

on:
  push:
    branches: [dev, staging, main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Deploy to Elastic Beanstalk
        run: |
          if [[ $GITHUB_REF == "refs/heads/dev" ]]; then
            npm run deploy:dev
          elif [[ $GITHUB_REF == "refs/heads/staging" ]]; then
            npm run deploy:staging
          elif [[ $GITHUB_REF == "refs/heads/main" ]]; then
            npm run deploy:prod
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
